baseURL = 'https://ameliayeah.github.io'
languageCode = 'en-us'
title = 'The Mel-ternet'
theme = "neopost"
titleCaseStyle = "none"

[params]
    theme = "dark-blue"
    author = "AmeliaYeah"

[permalinks]
    posts = "/posts/:year/:month/:day/:title"

[markup]
    [markup.highlight]
        lineNos = true
        style = "github-dark"