baseURL = 'https://ameliayeah.github.io'
languageCode = 'en-us'
title = 'Melancholia'
theme = "neopost"
titleCaseStyle = "none"

[params]
    theme = "dark-blue"
    author = "AmeliaYeah"

[permalinks]
    posts = "/posts/:year/:month/:day/:title"